In [1]:
import pandas as pd

data = pd.read_csv("data/menus_cleaned.csv")
data.head()

,restaurant,city,menu_type,category,dish,price,description,tags
0,Jack and Jacky's,Leeuwarden,Lunch,Bowls,AÇAI BOWL,13.2,"Açai, banaan, kokosdrink, granola, pindaswirl,...",NaN
1,Jack and Jacky's,Leeuwarden,Lunch,Bowls,CHEESECAKE OATS,10.8,"Overnight oats, Griekse yoghurt, aardbeienpure...",vegetarian
2,Jack and Jacky's,Leeuwarden,Lunch,Bowls,MANGO MADNESS BOWL,11.6,"Mango, banaan, kokosdrink, aardbei, granola, h...",vegetarian
3,Jack and Jacky's,Leeuwarden,Lunch,Bowls,BREAKFAST BOWL,10.1,"Griekse yoghurt, granola, banaan, chiazaad, bl...",vegetarian
4,Jack and Jacky's,Leeuwarden,Lunch,Pancakes,BERRY PANCAKES,14.6,"Bananen pannenkoekjes, Griekse yoghurtroom, ba...",vegetarian

In [4]:
data.shape

(641, 8)

In [3]:
# Checking for nan values
data.isna().sum()

restaurant       0
city             0
menu_type        0
category         0
dish             0
price            0
description    105
tags           171
dtype: int64

In [10]:
# Selecting only the rows with as category Salads
salads = data[data["category"] == "Salads"]
salads.head(20)

,restaurant,city,menu_type,category,dish,price,description,tags
16,Jack and Jacky's,Leeuwarden,Lunch,Salads,CHICKEN,14.9,"Gegrilde kip, avocado, crispy tuinbonen, komko...",meat
17,Jack and Jacky's,Leeuwarden,Lunch,Salads,SALMON,16.9,"Gerookte zalm, furikake, avocado, hoisin zuive...","fish, spicy"
18,Jack and Jacky's,Leeuwarden,Lunch,Salads,BURRATA,16.9,"Burrata, komkommer, vijgen, gerookte amandelen...",vegetarian
19,Jack and Jacky's,Leeuwarden,Lunch,Salads,CARPACCIO,15.3,"Rundercarpaccio, pesto, tomaat, komkommer, Par...",meat
20,Jack and Jacky's,Leeuwarden,Lunch,Salads,EXTRA'S,2.0,Glutenvrij brood,NaN
21,Jack and Jacky's,Leeuwarden,Lunch,Salads,KOFFIE,3.3,NaN,NaN
22,Jack and Jacky's,Leeuwarden,Lunch,Salads,AMERICANO,3.4,Iced / hot,NaN
23,Jack and Jacky's,Leeuwarden,Lunch,Salads,ESPRESSO,3.3,NaN,NaN
24,Jack and Jacky's,Leeuwarden,Lunch,Salads,DOUBLE ESPRESSO,3.8,NaN,NaN
25,Jack and Jacky's,Leeuwarden,Lunch,Salads,ESPRESSO MACCHIATO,3.5,NaN,NaN
26,Jack and Jacky's,Leeuwarden,Lunch,Salads,CAPPUCCINO,3.8,NaN,NaN
27,Jack and Jacky's,Leeuwarden,Lunch,Salads,CORTADO,3.5,NaN,NaN
28,Jack and Jacky's,Leeuwarden,Lunch,Salads,FLAT WHITE,4.3,NaN,NaN
29,Jack and Jacky's,Leeuwarden,Lunch,Salads,LATTE MACCHIATO,4.1,Iced / hot,NaN
30,Jack and Jacky's,Leeuwarden,Lunch,Salads,MOCHA COFFEE,4.5,NaN,NaN
31,Jack and Jacky's,Leeuwarden,Lunch,Salads,BABYCCINO,2.6,NaN,NaN
32,Jack and Jacky's,Leeuwarden,Lunch,Salads,COFFEE SHAKE,6.4,"Espresso, vanille-sojadrink, ijsklontjes & banaan",NaN
33,Jack and Jacky's,Leeuwarden,Lunch,Salads,FRESH MINT,3.9,NaN,NaN
34,Jack and Jacky's,Leeuwarden,Lunch,Salads,FRESH GINGER,3.9,NaN,NaN
35,Jack and Jacky's,Leeuwarden,Lunch,Salads,CHAMOMILE LAVENDER,3.6,NaN,meat